## The pair of functions, makeCacheMatrix and cacheSolve, are used to create a special 
## "matrix" object and caches its inverse.

## makeCacheMatrix creates a special "matrix" object that can cache its inverse.
## It contains four functions:
## 1) 'set' that sets the value of the matrix;
## 2) 'get' that gets the value of the matrix;
## 3) 'setinvmat' that sets the inverse of the matrix; and
## 4) 'getinvmat' that gets the inverse of the matrix.

makeCacheMatrix <- function(x = matrix()) {
        
        ## Sets the inverse of the matrix to null
        invmat <- NULL

        ## 'set' modifies the matrix x stored in makeCacheMatrix. 
        ## It is used if the matrix needs to be changed.
        set <- function (y){
                
                ## Replaces matrix x with matrix y in makeCacheMatrix.
                x <<- y  
                
                ## Restores the inverse of the matrix to null in makeCacheMatrix.
                ## The new matrix inversion will be generated by cacheSolve.
                invmat <<- NULL
        }
        
        ## 'get' returns the matrix x stored in makeCacheMatrix.
        ## It contains no arguments.  
        get <- function () x
        
        ## 'setinvmat' stores the inverse of matrix x in a object called invmat in makeCacheMatrix. 
        setinvmat <- function(solvemat) invmat <<- solvemat
        
        ## 'getinvmat' returns the inverse of matrix x in makeCacheMatrix. 
        ## It contains no arguments. 
        getinvmat <- function () invmat
        
        ## Stores all four functions in the main function makeCacheMatrix
        list (set=set, get=get, setinvmat=setinvmat, getinvmat=getinvmat)
}


## cacheSolve computes the inverse of the special "matrix" returned by makeCacheMatrix.  
## If the inverse has already been performed (and the matrix has not changed), then the
## cachesovle should retrieve the inverse from the cache.

cacheSolve <- function(x, ...) {
        
        ## Gets the inverse of the matrix stored in 'getinvmat' from makeCacheMatrix and assigns it to intmat
        invmat <- x$getinvmat()
        
        ## If the inverse of the matrix already exists and is not NULL, then output a message and the inversed matrix.
        ## cacheSolve ends
        if(!is.null(invmat)) {
                message ("getting cached data")
                return (invmat)
        }
        
        ## If the inverse of the matrix does not exist, then get the matrix stored in 'get' from makeCacheMatrix 
        ## and assigns it to mat
        mat <-x$get()      
        
        ## Inverses the matrix using the solve function and assigns the result to invmat
        invmat <- solve(mat)
        
        ## Sets the inversed matrix in the object generated in makeCacheMatrix 
        x$setinvmat(invmat)
        
        ## Returns the matrix that is the inverse of 'x'
        return(invmat)
}